site_name: Hidden Cavern Exploration

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.footer
  palette:
    - scheme: slate
      primary: deep purple  
      toggle:
        icon: material/brightness-7 
        name: Switch to light mode

    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
     
plugins:
- search
- mkdocstrings

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/AllanBirrellLYIT/Cavern-Exploration

copyright: Copyright &copy; 2024 Allan Birrell
